Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  ####### Provision #######
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "provision/watchlog.yml"
    ansible.verbose = true
  end

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "provision/apache.yml"
    ansible.verbose = true
  end
end
