Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
 
  config.vm.provision "shell", 
        inline: "(crontab -l 2>/dev/null; echo \"*/2 * * * * /vagrant/myscript.sh > /dev/null\") | crontab -" 
 
  config.vm.provision "shell", inline: <<-SHELL
        sudo yum install mailx -y
        mkdir -p /opt/etcd
        cd /tmp
        curl -L https://github.com/etcd-io/etcd/releases/download/v3.3.11/etcd-v3.3.11-linux-amd64.tar.gz -o etcd-v3.3.11-linux-amd64.tar.gz
        tar xzvf etcd-v3.3.11-linux-amd64.tar.gz
        mv /tmp/etcd-v3.3.11-linux-amd64/* /opt/etcd/
        ln -s /opt/etcd/etcdctl /usr/local/bin/etcdctl
        cd /opt/etcd
        ./etcd &
  SHELL
end
